### ISSUE TITLE
Composer issue with 12.3-RELEASE-p5

### ISSUE THREAD

**Issue by CesMak** [danb35/freenas-iocage-lychee#2]
503
../vendor/autoload.php not found.
Please do: composer install --no-dev --prefer-dist

Starting mysql.
Cloning into '/usr/local/www/Lychee'...
remote: Enumerating objects: 20976, done.
remote: Counting objects: 100% (2444/2444), done.
remote: Compressing objects: 100% (993/993), done.
remote: Total 20976 (delta 1623), reused 2142 (delta 1421), pack-reused 18532
Receiving objects: 100% (20976/20976), 135.27 MiB | 21.06 MiB/s, done.
Resolving deltas: 100% (15022/15022), done.
Do not run Composer as root/super user! See https://getcomposer.org/root for details
You are using Composer 1 which is deprecated. You should upgrade to Composer 2, see https://blog.packagist.com/deprecating-composer-1-support/
Loading composer repositories with package information
Installing dependencies from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for doctrine/dbal 3.3.6 -> satisfiable by doctrine/dbal[3.3.6].
    - doctrine/dbal 3.3.6 requires composer-runtime-api ^2 -> no matching package found.

Potential causes:
 - This package is not installable via Composer 1.x, see <https://blog.packagist.com/deprecating-composer-1-support/>
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
Command: sh -c cd /usr/local/www/Lychee/ && composer install --no-dev --prefer-dist failed!
PHP Warning:  require(/usr/local/www/Lychee/vendor/autoload.php): Failed to open stream: No such file or directory in /usr/local/www/Lychee/artisan on line 18
PHP Fatal error:  Uncaught Error: Failed opening required '/usr/local/www/Lychee/vendor/autoload.php' (include_path='.:/usr/local/share/pear') in /usr/local/www/Lychee/artisan:18
Stack trace:
#0 {main}
  thrown in /usr/local/www/Lychee/artisan on line 18
Command: sh -c cd /usr/local/www/Lychee/ && php artisan key:generate failed!
Successfully removed mount from lychee's fstab
Starting redis.
Performing sanity check on php-fpm configuration:
[12-Jun-2022 08:23:07] NOTICE: configuration file /usr/local/etc/php-fpm.conf test is successful

**how can I solve this issue?**

**Comment by danb35** [comment]
I've just modified the script to install Composer from getcomposer.org.  I've also updated it to use PHP 8.1 and add a couple of other dependencies.  To try it, first destroy the jail that was created (`iocage destroy lychee`), then remove the `/apps/lychee` directory from your pool.  Then change into the directory where you have this script and run `git pull`.  Then try running it again.
