### ISSUE TITLE
Caddy not starting after installation

### ISSUE THREAD

**Issue by CodyMoltar** [danb35/freenas-iocage-lychee#5]
Hi,

I ran your script to set up a jail and install Lychee.
When the script finishes ('Installation complete!') it also reports that Caddy was unable to start.

This is from the log file .../iocage/jails/lychee/root/var/log/caddy/caddy.log:
`{"level":"info","ts":1657710675.879874,"msg":"using provided configuration","config_file":"/usr/local/www/Caddyfile","config_adapter":"caddyfile"}
run: adapting config using caddyfile: parsing caddyfile tokens for 'log': /usr/local/www/Caddyfile:6 - Error during parsing: getting module named 'caddy.logging.encoders.single_field': module not registered: caddy.logging.encoders.>start: caddy process exited with error: exit status 1`

Seems like some module is deprecated? Found some info here:
https://caddy.community/t/error-module-not-registered-caddy-logging-encoders-single-field-encountered-after-upgrading-to-2-5-0/15763/1

**Comment by danb35** [comment]
Yeah, Caddy's author doesn't seem to be too concerned about backward-compatibility or human-readability.  If you want a quick fix, you can remove the "log format" line from the Caddyfile.  Or check out the script again with the fix I just merged.
